# Assignment 1

## Problem 1

In [ ]:
import numpy as np

arr = np.random.randint(1, 50, (5,4), dtype=int)

# print and get diagonal elements
print(f"Array:\n {arr}\n")

rows, cols = arr.shape
vec = []
for i in range(min(rows, cols)):
    vec.append(arr[i, cols-i-1])

print("Elements along the diagonals are: ")
print(vec)
print("-----------------------------------------------")


# max of each row
maxis = arr.max(axis=1)

print("\nMaximum elements of each row are: ")
print(maxis)
print("-----------------------------------------------")


# new array of elements less than mean
arr_mean = arr.mean()
print(f"\nMean of the array values is: {arr_mean}")
print("-----------------------------------------------")

new_arr = arr[arr <= arr_mean]
print("\nElements less than or equal to the mean:")
print(new_arr)
print("-----------------------------------------------")


# func to traverse boundary
def numpy_boundary_traversal(matrix):
    rows, cols = matrix.shape
    boundary = []

    for j in range(cols):
        boundary.append(matrix[0, j])

    for i in range(1, rows):
        boundary.append(matrix[i, cols - 1])

    if rows > 1:
        for j in range(cols - 2, -1, -1):
            boundary.append(matrix[rows - 1, j])

    if cols > 1:
        for i in range(rows - 2, 0, -1):
            boundary.append(matrix[i, 0])

    print("\nBoundary elements:")
    print(boundary)
    print("-----------------------------------------------")

numpy_boundary_traversal(arr)

Array:
 [[42 25 16  5]
 [29 37 41 32]
 [19  1 24  7]
 [34 49 25 26]
 [32 32 13 27]]

Elements along the diagonals are: 
[5, 41, 1, 34]
-----------------------------------------------

Maximum elements of each row are: 
[42 41 24 49 32]
-----------------------------------------------

Mean of the array values is: 25.8
-----------------------------------------------

Elements less than or equal to the mean:
[25 16  5 19  1 24  7 25 13]
-----------------------------------------------

Boundary elements:
[42, 25, 16, 5, 32, 7, 26, 27, 13, 32, 32, 34, 19, 29]
-----------------------------------------------


## Problem 2

In [11]:
arr = np.random.uniform(0, 10, 20)

print(f"The array: \n{arr}")
print("-----------------------------------------------")

#print and roundoff
rounded_arr = np.round(arr, 2)
print(f"\nThe rounded off array is: \n{rounded_arr}")
print("-----------------------------------------------")


#min, max and median finding
mini = rounded_arr.min()
maxi = rounded_arr.max()
median = np.median(rounded_arr)

print(f"\nMinimum is: {mini}")
print(f"\nMaximum is: {maxi}")
print(f"\nMedian is: {median}")
print("-----------------------------------------------")


#elements less than 5, to its squares
for i in range(len(rounded_arr)):
    if(rounded_arr[i]<5):
        rounded_arr[i] *= rounded_arr[i]

print(f"\nThe array after squaring elements less than 5 is: \n{rounded_arr}")
print("-----------------------------------------------")


#func to sort
def numpy_alternate_sort(array):
    temp = np.sort(array)
    ans = []
    i=0
    j=len(temp)-1
    while i<=j:
        if i == j:
            ans.append(temp[i])
            break
        else:
            ans.append(temp[i])
            ans.append(temp[j])
        i += 1
        j -= 1
    return np.array(ans)

numpy_alternate_sort(rounded_arr)

The array: 
[4.40207361 9.5372889  1.27965941 2.1648431  0.13916966 9.21767211
 3.60539474 1.03740036 9.12507864 1.57352299 1.42738197 6.94462312
 5.1352576  2.31072899 2.54628278 8.23927698 5.28561274 7.80082568
 8.6032791  7.58278296]
-----------------------------------------------

The rounded off array is: 
[4.4  9.54 1.28 2.16 0.14 9.22 3.61 1.04 9.13 1.57 1.43 6.94 5.14 2.31
 2.55 8.24 5.29 7.8  8.6  7.58]
-----------------------------------------------

Minimum is: 0.14

Maximum is: 9.54

Median is: 4.77
-----------------------------------------------

The array after squaring elements less than 5 is: 
[19.36    9.54    1.6384  4.6656  0.0196  9.22   13.0321  1.0816  9.13
  2.4649  2.0449  6.94    5.14    5.3361  6.5025  8.24    5.29    7.8
  8.6     7.58  ]
-----------------------------------------------


array([ 0.0196, 19.36  ,  1.0816, 13.0321,  1.6384,  9.54  ,  2.0449,
        9.22  ,  2.4649,  9.13  ,  4.6656,  8.6   ,  5.14  ,  8.24  ,
        5.29  ,  7.8   ,  5.3361,  7.58  ,  6.5025,  6.94  ])

## Problem 3

In [32]:
import pandas as pd

subjects = ['Maths', 'Physics', 'Chemistry']

df = pd.DataFrame({
    "Name": ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'],
    "Subject": np.random.choice(subjects, size=10),
    "Score": np.random.randint(50, 101, size=10),
    "Grade": ['']*10
})

print(f"Initial DF: \n{df}")
print("-----------------------------------------------")


#Assign grades
for i in range(10):
    if df['Score'][i] >= 90:
        df.loc[i, 'Grade'] = 'A'
    elif df['Score'][i] >= 80:
        df.loc[i, 'Grade'] = 'B'
    elif df['Score'][i] >= 70:
        df.loc[i, 'Grade'] = 'C'
    elif df['Score'][i] >= 60:
        df.loc[i, 'Grade'] = 'D'
    else:
        df.loc[i, 'Grade'] = 'F'

print(f"After Assigning grades: \n{df}")
print("-----------------------------------------------")


#sort in descending
df = df.sort_values('Score', ascending=False)
print(f"In descending order of scores: \n{df}")
print("-----------------------------------------------")


# avg for each subject
avgs = df.groupby('Subject')['Score'].mean()

print(f"Averages for each sub: \n{avgs.round(2)}")
print("-----------------------------------------------")


# func to filter grades
def pandas_filter_pass(dataframe):
    newdf = dataframe[(dataframe['Grade'] == 'A') | (dataframe['Grade'] == 'B')]
    return newdf

filtered_df = pandas_filter_pass(df)
print(f"Students with only A and B grades: \n{filtered_df}")
print("-----------------------------------------------")

Initial DF: 
  Name    Subject  Score Grade
0    a  Chemistry     63      
1    b    Physics     99      
2    c    Physics     97      
3    d    Physics     75      
4    e  Chemistry     59      
5    f    Physics     59      
6    g  Chemistry     83      
7    h      Maths     61      
8    i    Physics     84      
9    j      Maths     84      
-----------------------------------------------
After Assigning grades: 
  Name    Subject  Score Grade
0    a  Chemistry     63     D
1    b    Physics     99     A
2    c    Physics     97     A
3    d    Physics     75     C
4    e  Chemistry     59     F
5    f    Physics     59     F
6    g  Chemistry     83     B
7    h      Maths     61     D
8    i    Physics     84     B
9    j      Maths     84     B
-----------------------------------------------
In descending order of scores: 
  Name    Subject  Score Grade
1    b    Physics     99     A
2    c    Physics     97     A
8    i    Physics     84     B
9    j      Maths     84    

## Problem 4

In [ ]:

import random
positive_phrases = [
    "I loved the movie", "Amazing storyline", "Great acting", "Fantastic direction",
    "Enjoyed every moment", "Brilliant performance", "Superb movie", "Highly recommended",
    "Wonderful experience", "Outstanding film"
]

negative_phrases = [
    "I hated the movie", "Terrible storyline", "Bad acting", "Poor direction",
    "Waste of time", "Disappointing performance", "Awful movie", "Not recommended",
    "Horrible experience", "Worst film ever"
]


positive_reviews = np.random.choice(positive_phrases, 50)
negative_reviews = np.random.choice(negative_phrases, 50)

reviews = np.concatenate([positive_reviews, negative_reviews])
sentiments = ['positive'] * 50 + ['negative'] * 50

combined = list(zip(reviews, sentiments))
random.shuffle(combined)
df = pd.DataFrame(combined, columns=['Review', 'Sentiment'])

print(df.head())

                 Review Sentiment
0       Worst film ever  negative
1     I loved the movie  positive
2          Great acting  positive
3  Enjoyed every moment  positive
4        Poor direction  negative


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

#tokenize reviews
vectorizer = CountVectorizer(stop_words='english', max_features=500)

X = vectorizer.fit_transform(df['Review'])
y = df['Sentiment'].map({'positive': 1, 'negative': 0})


#test-train split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


#model training
model = MultinomialNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", accuracy)


#predict sentiments func
def predict_review_sentiment(model, vectorizer, review):
    review_vector = vectorizer.transform([review])
    prediction = model.predict(review_vector)
    sentiment = 'positive' if prediction[0] == 1 else 'negative'
    return sentiment

sample_review = "The movie was absolutely fantastic"
result = predict_review_sentiment(model, vectorizer, sample_review)
print("Predicted Sentiment:", result)

Test Accuracy: 1.0
Predicted Sentiment: positive


## Problem 5

In [44]:
import numpy as np
import pandas as pd
import random
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report


In [47]:
good_feedback = [
    "Excellent product", "Very satisfied", "Works perfectly", "Highly recommend it",
    "Five stars", "Loved the quality", "Amazing performance", "Exceeded expectations",
    "Fast delivery", "Top-notch service"
]

bad_feedback = [
    "Terrible product", "Very disappointed", "Does not work", "Would not recommend",
    "One star", "Poor quality", "Awful experience", "Did not meet expectations",
    "Slow delivery", "Worst service ever"
]

good_reviews = [random.choice(good_feedback) + random.choice(["!", ".", "", " Really nice."]) for _ in range(50)]
bad_reviews = [random.choice(bad_feedback) + random.choice(["!", ".", "", " So bad."]) for _ in range(50)]

texts = good_reviews + bad_reviews
labels = ['good'] * 50 + ['bad'] * 50

combined = list(zip(texts, labels))
random.shuffle(combined)

df = pd.DataFrame(combined, columns=['Feedback', 'Label'])


In [49]:
#process text
vectorizer = TfidfVectorizer(stop_words='english', max_features=300, lowercase=True)

X = vectorizer.fit_transform(df['Feedback'])
y = df['Label'].map({'good': 1, 'bad': 0})

# test-train spilt
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)


#train model
model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Classification Report:\n")
print(classification_report(y_test, y_pred, target_names=['bad', 'good']))
print("-----------------------------------------------")


#func to vectorize
def text_preprocess_vectorize(texts, vectorizer):
    return vectorizer.transform(texts)

sample_texts = ["Great product and service", "Worst thing I ever bought"]
vec_output = text_preprocess_vectorize(sample_texts, vectorizer)

print("\nVectorized shape:", vec_output.shape)


Classification Report:

              precision    recall  f1-score   support

         bad       0.92      1.00      0.96        12
        good       1.00      0.92      0.96        13

    accuracy                           0.96        25
   macro avg       0.96      0.96      0.96        25
weighted avg       0.96      0.96      0.96        25

-----------------------------------------------

Vectorized shape: (2, 33)
